[package]
name = "portinfo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.32"
owo-colors = "4.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
termion = "4.0.4"
textwrap = "0.16.2"

[[bin]]
name = "portinfo"
path = "src/main.rs"
