[package]
name = "serde_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
owo-colors = "4.2.0"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
termion = "4.0.4"
textwrap = "0.16.2"

[lib]
proc-macro = true
